### ISSUE TITLE
Support for specific version

### ISSUE THREAD

**Issue by arthur-fontaine** [HiDeoo/npm-package-manager-extension#14]
### Is your feature request related to a problem?

When I am on https://www.npmjs.com/package/some-package/v/1.0.0-beta.0, I think the "Install" command should include the version.

---

**_Example_**

When I am on https://www.npmjs.com/package/some-package/v/1.0.0-beta.0, show
```
pnpm add some-package@1.0.0-beta.0
```

### Describe the solution you'd like

Parsing the URL, get the part after `/v/{this part}` and add it to the command.

**Comment by HiDeoo** [comment]
Thanks for your feedback.

> When I am on [npmjs.com/package/some-package/v/1.0.0-beta.0](https://www.npmjs.com/package/some-package/v/1.0.0-beta.0), I think the "Install" command should include the version.

This is a totally valid suggestion.

It turns out the extension is already having this behavior in a __very specific__ case:

- The `npmjs.com/package/<package>/v/<version>` is loaded directly.
- The `<version>` is not the latest version.

Altho, this behavior is not working for the following cases:

- The URL is loaded directly and `<version>` is the latest version.
- The URL is navigated to from the unversioned package page, e.g. by clicking on the `X Versions` tab and selecting a version.

Supporting all these cases requires a bit of refactoring and adding a service worker to listen to navigation events but this is not a big deal. I also think the behavior should also be a little bit different from the default npmjs.com one and always include the version in the install commands when the URL contains a specific version (no matter how the URL was loaded).

I have a working prototype for this on a local branch that just needs some polishing and testing. I'll try to get it out as soon as possible and make sure to ping this issue when available.

**Comment by HiDeoo** [comment]
`v0.3.0` including this new feature has been submitted for review on both the Chrome Web Store and the Microsoft Edge Add-ons Marketplace.

The Chrome Web Store review process is usually pretty fast, like 1 day but the Microsoft Edge Add-ons Marketplace is slower, around 1 week usually. I expect this update to take a bit more time tho as the extension now requires a new additional permission.

I'll update this issue when this new version in available on the various stores.

**Comment by HiDeoo** [comment]
`v0.3.0` should now be available on both the [Chrome Web Store](https://chrome.google.com/webstore/detail/npm-package-manager/mkflcfbfnijaofdeeflecnjlooefmcka) and the [Microsoft Edge Add-ons Marketplace](https://microsoftedge.microsoft.com/addons/detail/npm-package-manager/oogocgnfebpilcfmlgdencdmemicdaoo).

Note that existing users should get a prompt for the new permission to re-enable the extension after the update.

Thanks again for your suggestion.
